Weapon.create(name: 'MP7(SMG)', image_url: 'MP7.png', description: 'とても使いやすいSMG。武器選びに困ったらこれ。')
Weapon.create(name: 'PDW-57(SMG)', image_url: 'PDW-57.png', description: '弾数多いがキルレート低め。エイムが不安ならこれ。')
Weapon.create(name: 'Vector K10(SMG)', image_url: 'Vector K10.png', description: 'とても使いやすいSMG。でもこれ使うならMP7使う')
Weapon.create(name: 'MSMC(SMG)', image_url: 'MSMC.png', description: '近距離最強クラス。SMGで1番使った。')
Weapon.create(name: 'Chicom CQB(SMG)', image_url: 'Chicom CQB.png', description: 'カスタムクラスにあったからプレステージ回した後にチャレンジしてた。')
Weapon.create(name: 'Skorpion EVO III(SMG)', image_url: 'Skorpion.png', description: '暴れすぎて嫌い')
Weapon.create(name: 'Peacekeeper(SMG)', image_url: 'Peacekeeper.png', description: '課金武器。落ちてたら使う。')
Weapon.create(name: 'MTAR(AR)', image_url: 'MTAR.png', description: '普通に使いやすいAR。特徴がないのが特徴。')
Weapon.create(name: 'Type 25(AR)', image_url: 'Type 25.png', description: 'SMGっぽいAR。SMGでよくね？')
Weapon.create(name: 'SWAT-556(AR)', image_url: 'SWAT-556.png', description: '3点バーストのAR。M8A1でよくね？')
Weapon.create(name: 'FAL OSW(AR)', image_url: 'FAL OSW.png', description: 'セミオートのAR。ヘッショチャレンジきつかったorz')
Weapon.create(name: 'M27(AR)', image_url: 'M27.png', description: '覚えてな（ｒｙ')
Weapon.create(name: 'SCAR-H(AR)', image_url: 'SCAR-H.png', description: 'AR最強候補。暴れやすいが高威力。1番好き。')
Weapon.create(name: 'SMR(AR)', image_url: 'SMR.png', description: 'セミオートのAR。威力高いけどヘッショ1発じゃないからクソ')
Weapon.create(name: 'M8A1(AR)', image_url: 'M8A1.png', description: '4点バーストのAR。偶に使うと楽しい。')
Weapon.create(name: 'AN-94(AR)', image_url: 'AN-94.png', description: 'AR最強候補。最初の2発の弾速がめちゃ早い。2番目に好き')
Weapon.create(name: 'Remington 870 MCS(SG)', image_url: 'Remington 870 MCS.png',
              description: 'ショットガンの中で1番使いやすく強い。角待ちして相手の断末魔を聞くのが楽しい。')
Weapon.create(name: 'S12(SG)', image_url: 'S12.png', description: 'セミオートのショットガン。回線悪いと1発で死んだように見える')
Weapon.create(name: 'KSG(SG)', image_url: 'KSG.png', description: 'ポンプアクションのショットガン。遠距離も1発だが要エイム。1発で死ななかったら終わり')
Weapon.create(name: 'M1216(SG)', image_url: 'M1216.png', description: '4連発フルオートのショットガン。適当に打っても楽しい')
Weapon.create(name: 'Mk 48(LMG)', image_url: 'Mk48.png', description: 'LMGと言えばこれ。2階でこれ持って籠ってるだけで気持ちいい。')
Weapon.create(name: 'QBB LSW(LMG)', image_url: 'QBB LSW.png', description: 'レート速すぎて近距離用LMG。SMGでええやん。')
Weapon.create(name: 'LSAT(LMG)', image_url: 'LSAT.png', description: '悪くはないことが悪い。微妙な性能。')
Weapon.create(name: 'HAMR(LMG)', image_url: 'HAMR.png', description: '強くはないけど弱くもない。')
Weapon.create(name: 'SVU-AS(SR)', image_url: 'SVU-AS.png', description: 'ゴミ。初期からなかったら迷彩チャレンジしてなかったかも')
Weapon.create(name: 'DSR-50(SR)', image_url: 'DSR 50.png', description: 'やりきれないことが少ないSR。高威力で好き。凸砂するのはちょっときつい。')
Weapon.create(name: 'Ballista(SR)', image_url: 'Ballista.png', description: '凸砂するならこれ。尚、アイアンサイトは嫌い')
Weapon.create(name: 'XPR-50(SR)', image_url: 'XPR-50.png', description: 'ヘッショで1発だからまだ許せる。')
Weapon.create(name: 'Assault Shield', image_url: 'Assault Shield.png',
              description: '背中を任せられる頼れる相棒。バリスティックナイフで凸るならセットで使う。')
Weapon.create(name: 'Five-seven(HG)', image_url: 'Five-seven.png', description: '普通。')
Weapon.create(name: 'Tac .45(HG)', image_url: 'Tac-45.png', description: '2発キルできるので良き。SRのお供はこれ')
Weapon.create(name: 'B23R(HG)', image_url: 'B23R.png', description: '指切りしなくてもいいからラク。威力も悪くない。')
Weapon.create(name: 'Executioner(HG)', image_url: 'Executioner.png', description: 'HGよりSGみたいな立ち回りが必要。あんまり好きじゃない')
Weapon.create(name: 'KAP-40(HG)', image_url: 'KAP-40.png', description: 'フルオートHG。普通に強い。けど出てくるの遅いからあんまり使えない。')
Weapon.create(name: 'SMAW(ランチャー)', image_url: 'SMAW.png', description: '真っ直ぐ飛んでくれるから好き。')
Weapon.create(name: 'FHJ-18 AA(ランチャー)', image_url: 'FHJ-18 AA.png', description: '航空機落とすならこれ。')
Weapon.create(name: 'RPG(ランチャー)', image_url: 'RPG.png', description: '直撃キル10キルは多いって。なんで目の前にいるのに外れるんや。')
Weapon.create(name: 'Crossbow', image_url: 'Crossbow.png', description: '遠距離で撃ち合うの楽しい。')
Weapon.create(name: 'Ballistic Knife', image_url: 'Ballistic Knife.png', description: '刃先が飛んでいくの楽しい')
Weapon.create(name: 'Combat Knife', image_url: 'knife.png', description: '芋狩りするならこれ')
